name: Telegram Poll

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * TUE'

jobs:
  send-poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Send poll via Docker Compose
        env:
          BOT_TOKEN:      ${{ secrets.BOT_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          POLL_QUESTION:  ${{ secrets.POLL_QUESTION }}
          POLL_OPTIONS:   ${{ secrets.POLL_OPTIONS }}
          POLL_ANONYMOUS: ${{ secrets.POLL_ANONYMOUS }}
          POLL_MULTIPLE:  ${{ secrets.POLL_MULTIPLE }}
        run: docker-compose run --rm pollbot
